#!/usr/bin/env bash

# download
curl -s https://api.github.com/repos/Kaelten/OneCore/releases/latest |
    jq '.assets[] | select(.name | endswith(".zip")) | .browser_download_url' |
    tr -d \" |
    xargs curl -sL -o OneCore.zip

# unpack
unzip -o OneCore.zip -d libs

# cleanup
rm -f OneCore.zip
