name: Pull Requests

on: [pull_request]

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # gets entire git history, needed for automatic changelogs

      - name: luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: download latest onecore
        run: .scripts/download-latest-onecore

      - name: package and deploy
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }} # don't upload onecore to wowi
        with:
          args: -d -z

      - name: attach PR artifact
        uses: actions/upload-artifact@v3
        with:
          name: OneCore-PR${{ github.event.number }}-${{ github.sha }}
          path: .release/
